<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414130950 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE town (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, postal_code VARCHAR(255) NOT NULL, longitude DOUBLE PRECISION NOT NULL, latitude DOUBLE PRECISION NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, department_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4CE6C7A4AE80F5DF ON town (department_id)');
        $this->addSql('ALTER TABLE town ADD CONSTRAINT FK_4CE6C7A4AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE town DROP CONSTRAINT FK_4CE6C7A4AE80F5DF');
        $this->addSql('DROP TABLE town');
    }
}
